on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner to run the build on.'
        required: true
        type: string
      os:
        description: 'Name of the runner OS.'
        required: true
        type: string
      compiler:
        description: 'Compiler to build with.'
        required: true
        type: string
      build_type:
        description: 'CMake build type.'
        required: true
        type: string
      save-cache:
        description: 'Save build and Python virtual environment to cache.'
        required: false
        type: boolean
        default: false
      build-modules:
        description: 'Build with modules enabled.'
        required: false
        type: boolean
        default: false
      upload-artifact:
        description: 'Upload built executables.'
        required: false
        type: boolean
        default: false
      summarize:
        description: 'Output build summary.'
        required: false
        type: boolean
        default: false

jobs:
  Build:
    name: ${{ format('Build ({0}, {1})', inputs.runner, inputs.compiler) }}
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash
    env:
      CMAKE_BUILD_TYPE: ${{ inputs.build_type }}
      SCCACHE_DIR: ${{ format('{0}/sccache', github.workspace) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies (Brew)
        if: ${{ runner.os == 'macOS' }}
        run: brew install mariadb zeromq zmq luajit

      - name: Install dependencies (APT)
        if: ${{ inputs.os == 'Ubuntu' }}
        run: |
          sudo apt-get update && sudo apt-get install --assume-yes --no-install-recommends --quiet \
            binutils-dev \
            g++-14 \
            libluajit-5.1-dev \
            libmariadb-dev-compat \
            libssl-dev \
            libzmq3-dev \
            mariadb-client \
            python3-venv \
            tzdata \
            zlib1g-dev

      # If libc++ build is wanted (Alpine uses this with Clang20)
      # - name: Install Clang
      #   if: ${{ inputs.os == 'Ubuntu' && inputs.compiler == 'clang18' }}
      #   run: |
      #     sudo apt-get update && sudo apt-get install --assume-yes --no-install-recommends --quiet \
      #       clang-18 \
      #       lld-18 \
      #       libc++-18-dev \
      #       libc++abi-18-dev \
      #       libclang-rt-18-dev \
      #       libunwind-18-dev

      - name: Setup MSVC
        if: ${{ runner.os == 'Windows' }}
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Restore Python virtual environment
        id: restore_python
        uses: actions/cache/restore@v4
        env:
          hash: ${{ hashFiles('./tools/requirements.txt') }}
          ref: ${{ github.base_ref || github.ref_name }}
        with:
          path: .venv
          key: ${{ format('venv-{0}-{1}-{2}', inputs.os, env.hash, env.ref) }}

      - name: Install Python dependencies
        env:
          venv_scripts: ${{ runner.os == 'Windows' && 'Scripts' || 'bin' }}
        run: |
          python3 -m venv .venv
          source ${{ format('.venv/{0}/activate', env.venv_scripts) }}
          python -m pip install -r ./tools/requirements.txt

      - name: Restore build cache
        id: restore_build
        uses: actions/cache/restore@v4
        env:
          cmake_hash: ${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          source_hash: ${{ hashFiles('src/**/*', 'ext/**/*') }}
          ref: ${{ github.base_ref || github.ref_name }}
        with:
          path: |
            build
            ${{ env.SCCACHE_DIR }}
          key: ${{ format('buildcache-{0}-{1}-{2}-{3}-{4}-{5}', inputs.os, inputs.compiler, inputs.build_type, env.ref, env.cmake_hash, env.source_hash) }}
          restore-keys: |
            ${{ format('buildcache-{0}-{1}-{2}-{3}-{4}-', inputs.os, inputs.compiler, inputs.build_type, env.ref, env.cmake_hash) }}

      # TODO: only do this if src modules changed.
      - name: Enable modules
        if: ${{ inputs.build-modules }}
        run: |
          python3 <<EOF
          with open("modules/init.txt", "w") as f:
              f.write("custom\n")
              f.write("era\n")
              f.write("example\n")
              f.write("renamer\n")
          EOF

      - name: Configure CMake
        run: |
          cp -p build/xi_* . 2> /dev/null || true
          if [[ ${{ inputs.os }} == 'Ubuntu' ]]; then
              if [[ ${{ inputs.compiler }} == 'clang18' ]]; then
                  export CC=/usr/bin/clang-18
                  export CXX=/usr/bin/clang++-18
                  # export CXXFLAGS="-stdlib=libc++"
                  # export LDFLAGS="-fuse-ld=lld -lstdc++"
              else
                  export CC=/usr/bin/gcc-14
                  export CXX=/usr/bin/g++-14
              fi
          fi
          cmake -G Ninja -S . -B build \
            -DTRACY_ENABLE=ON \
            -DENABLE_CLANG_TIDY=${{ inputs.os == 'Ubuntu' && inputs.compiler == 'clang18' && 'ON' || 'OFF' }} \
            -DPCH_ENABLE=${{ runner.os == 'Windows' && inputs.build_type == 'Debug' && 'OFF' || 'ON' }} \
            -DCACHE_OPTION=sccache

      - name: Build
        run: |
          cmake --build build | tee build.log
          cp -p xi_* build/

      - name: Summarize Build
        if: ${{ inputs.summarize }}
        run: |
          echo "## Build Log" >> $GITHUB_STEP_SUMMARY
          if [[ -f "build.log" && -s "build.log" ]]; then
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              cat build.log >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('LSB_{0}_{1}_{2}', inputs.os, inputs.build_type, github.sha) }}
          path: |
                xi_*
                tracy.tar.gz

      - name: Cache Python virtual environment
        if: ${{ inputs.save-cache && !steps.restore_python.outputs.cache-hit }}
        uses: actions/cache/save@v4
        env:
          hash: ${{ hashFiles('./tools/requirements.txt') }}
          ref: ${{ github.base_ref || github.ref_name }}
        with:
          path: .venv
          key: ${{ format('venv-{0}-{1}-{2}', inputs.os, env.hash, env.ref) }}

      - name: Cache build
        if: ${{ inputs.save-cache && !steps.restore_build.outputs.cache-hit }}
        uses: actions/cache/save@v4
        env:
          cmake_hash: ${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          source_hash: ${{ hashFiles('src/**/*', 'ext/**/*') }}
          ref: ${{ github.base_ref || github.ref_name }}
        with:
          path: |
            build
            ${{ env.SCCACHE_DIR }}
          key: ${{ format('buildcache-{0}-{1}-{2}-{3}-{4}-{5}', inputs.os, inputs.compiler, inputs.build_type, env.ref, env.cmake_hash, env.source_hash) }}
